name: ZFSWatcher Makefile CI

on:
  push:
    branches:
      - contrib
  pull_request:
    branches:
      - contrib

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Install pre-reqs
      run: sudo apt-get update && sudo apt-get install -y rpm dpkg-dev debhelper
      
    - name: Clean build environment
      run: make clean
      
    - name: Build ZFSWatcher
      run: make
      
    - name: Build Tarball
      run: make dist
      
    - name: Upload Tarball
      uses: actions/upload-artifact@v2
      with:
        name: ZFSWatcher Tarball
        path: '*.tar.*'

    - name: Build Debian package
      run: make deb
      
    - name: Upload Debian package and changelog  
      uses: actions/upload-artifact@v2
      with:
        name: ZFSWatcher DEB and Changelog
        path: |
          *.deb
          *.changes
    
    - name: Build RPM packages
      run: make rpm
      
    - name: Upload RPM packages  
      uses: actions/upload-artifact@v2
      with:
        name: ZFSWatcher RPMs
        path: '*.rpm'

    - name: Publish pre-release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        draft: true
        automatic_release_tag: latest-dev
        title: Development Build
        files: |
          *.rpm
          *.deb
